DROP TABLE "Users" CASCADE;

-- Create user table
CREATE TABLE IF NOT EXISTS "Users" (
    id bigint generated by default as identity, 
    name varchar(255), 
    password varchar(255), 
    primary key (id)
);


INSERT INTO "Users" (name, password) VALUES ('admin', 'admin123');
