--DROP TABLE "Users" CASCADE;

-- Create user table
CREATE TABLE IF NOT EXISTS "Users" (
    id bigint generated by default as identity, 
    name varchar(255), 
    password varchar(255), 
    primary key (id)
);

-- Unique name
CREATE UNIQUE INDEX IF NOT EXISTS users_name_unique_idx ON "Users"(name);
