--DROP TABLE "Users" CASCADE;

-- Create User table
CREATE TABLE IF NOT EXISTS "Users" (
    id bigint generated by default as identity, 
    name varchar(255), 
    password varchar(255), 
    primary key (id)
);

-- Unique User name
CREATE UNIQUE INDEX IF NOT EXISTS users_name_unique_idx ON "Users"(name);

--Create todos table
CREATE TABLE IF NOT EXISTS "Todos" (
    id bigint generated by default as identity,
    title varchar(255),
    status varchar(255),
    owner_id bigint REFERENCES "Users"(id),
    created_at TIMESTAMP default CURRENT_TIMESTAMP,
    primary key (id)
);
